name       : perl-data-validate-ip
version    : 0.27
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Data-Validate-IP-0.27.tar.gz : e1aa92235dcb9c6fd9b6c8cda184d1af73537cc77f4f83a0f88207a8bfbfb7d6
homepage   : https://metacpan.org/release/Data-Validate-IP
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : IPv4 and IPv6 validation methods 
description: |
    This module collects IP address validation routines to make input validation, and untainting easier and more readable.
runddeps   :
    - perl-netaddr-ip
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
