name       : perl-data-validate-ip
version    : '0.30'
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Data-Validate-IP-0.30.tar.gz : fe2f7663e18b70d5510529c22f45fdd2bbdb4a5adb26d65c9050c5b9696e8a1c
homepage   : https://metacpan.org/pod/Data::Validate::IP
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Data::Validate::IP - IPv4 and IPv6 validation methods
description: |
    This module provides a number IP address validation subs that both validate and untaint their input. This includes both basic validation (is_ipv4() and is_ipv6()) and special cases like checking whether an address belongs to a specific network or whether an address is public or private (reserved).
runddeps   :
    - perl-netaddr-ip
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
